apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transformers
  namespace: default
spec:
  releaseName: transformers
  install:
    remediation:
      retries: -1
    timeout: 20m0s
  chart:
    spec:
      version: ">=0.0.1"
  test:
    enable: false
  values:
    serviceInfo:
      name: "transformers"
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      cloud.google.com/gke-accelerator-count: "1"
    image: 484097152182.dkr.ecr.us-east-1.amazonaws.com/transformers:v7
    resources:
      requests:
        nvidia.com/gpu: "1"
        cpu: "2"
        memory: "8Gi"
        ephemeral-storage: "10Gi"
