apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops
  namespace: default
spec:
  interval: 1m0s
  url: https://github.com/webaverse-studios/gitops-infinitia.git
  ref:
    branch: main
  secretRef:
    name: git-creds
