apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: base-image-repo
  namespace: flux-system
spec:
  suspend: false
  image: base-image-repo
  interval: 5m0s
  secretRef:
    name: ecr-credentials
  accessFrom:
    namespaceSelectors:
      - matchLabels: {}