apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- image-automation.yaml
- ../../../infrastructure/base

# This patch allows cluster autoscaler to evict the Flux controller pods as we are not controlling nodes
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          metadata:
            annotations:
              cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux

#  - patch: |
#      apiVersion: v1
#      kind: ServiceAccount
#      metadata:
#        name: image-reflector-controller
#        annotations:
#          iam.gke.io/gcp-service-account: "aws-service-account@wav-develop.iam.gserviceaccount.com"
#    target:
#      kind: ServiceAccount
#      name: image-reflector-controller