apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infrastructure/base/ingress

patches:
  - path: ingress-alpha.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ingress-base
    options:
      allowNameChange: true