apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infrastructure/base/config

patches:
  - path: custom-backend.yaml
    target:
      group: cloud.google.com
      version: v1
      kind: BackendConfig
      name: custom-backendconfig
    options:
      allowNameChange: true

  - path: custom-backend-default.yaml
    target:
      group: cloud.google.com
      version: v1
      kind: BackendConfig
      name: custom-backendconfig-default
    options:
      allowNameChange: true

  - path: root-backend-default.yaml
    target:
      group: cloud.google.com
      version: v1
      kind: BackendConfig
      name: root-backendconfig-default
    options:
      allowNameChange: true
