apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: root-backendconfig-default
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 30
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 80