apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceInfo.name }}-svc"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": {{ .Values.service.backendConfig | quote }}}'
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: "{{ .Values.serviceInfo.name }}"
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
      protocol: TCP
